### Para ver todos los productos (con paginación por defecto page=1, limit=20)
GET http://localhost:4000/productos

### Para ver productos paginados especificando página y límite
GET http://localhost:4000/productos?page=1&limit=20

### Para filtrar productos por categoria y paginar
GET http://localhost:4000/productos?categoria=Placas de Video&page=1&limit=5

### Para filtrar productos por subcategoria
GET http://localhost:4000/productos?subcategoria_id=1

### Para ver un producto por su id
GET http://localhost:4000/productos/3e27aaeb-a7ca-417b-bc63-562f772e3406

### Para crear un producto
POST http://localhost:4000/productos
Content-Type: application/json

{
    "nombre": "RTX 5060",
    "descripcion": "Tarjeta gráfica NVIDIA RTX 5060 8GB GDDR7",
    "precio": 420.00,
    "stock": 15,
    "img_url": "https://fakestoreapi.com/img/81fAn9+IfdL._AC_UY879_.jpg",
    "public_id": "temp",
    "categoria_id": 4,
    "subcategoria_id": 1,
    "caracteristicas": [
        { "clave": "VRAM", "valor": "8GB" },
        { "clave": "Memoria", "valor": "GDDR7" },
        { "clave": "Bus", "valor": "128-bit" }
    ]
}

### Para editar un producto
PATCH http://localhost:4000/productos/b10425ea-fd3f-4fff-b580-4c6361f48770
Content-Type: application/json

{
    "stock": 20
}

### Para eliminar un producto
DELETE http://localhost:4000/productos/3e27aaeb-a7ca-417b-bc63-562f772e3406

### Para ver todas las categorias
GET http://localhost:4000/categorias

### Para crear una categoria
POST http://localhost:4000/categorias
Content-Type: application/json

{
    "nombre": "Mandos"    
}

### Para eliminar una categoria
DELETE http://localhost:4000/categorias/13

### Para ver todas las subcategorias
GET http://localhost:4000/subcategorias

### Para filtrar subcategorias por categoria_id (Select dependiente)
GET http://localhost:4000/subcategorias?categoria_id=1

### Para crear una subcategoria (solo ADMIN)
POST http://localhost:4000/subcategorias
Content-Type: application/json

{
    "nombre": "Fuentes de Alimentación",
    "categoria_id": 1
}

### Para eliminar una subcategoria (solo ADMIN)
DELETE http://localhost:4000/subcategorias/1

### Para registrarse
POST http://localhost:4000/auth/register
Content-Type: application/json

{
    "nombre": "juan",
    "email": "juan@gmail.com",
    "password": "12345678"
}

### Para iniciar Sesion
POST http://localhost:4000/auth/login
Content-Type: application/json

{
    "email": "gabriel@gmail.com",
    "password": "87654321"
}

### Para cerrar sesion
POST http://localhost:4000/auth/logout

### Para recuperar la contraseña
POST http://localhost:4000/auth/update-password
Content-Type: application/json

{
    "password": "12345678",
    "newPassword": "87654321"
}

### Para ver todos los usuarios
GET http://localhost:4000/usuarios

### Para ver el perfil
GET http://localhost:4000/usuarios/perfil

### Para crear los datos de facturacion
POST http://localhost:4000/usuarios/datos-facturacion
Content-Type: application/json

{
    "nombre_completo": "Gabriel Fernández",
    "dni": "12345678",
    "direccion": "Av. Siempre Viva 742",
    "ciudad": "Tucumán",
    "provincia": "Tucumán",
    "codigo_postal": "4000"
}

### Para actualizar los datos de facturacion
PATCH http://localhost:4000/usuarios/datos-facturacion
Content-Type: application/json

{
    "codigo_postal": "4420"
}

### Para que el admin elimine una cuenta
DELETE http://localhost:4000/usuarios/2

### Para ver las ordenes
GET http://localhost:4000/ordenes

### Para ver una orden por su id
GET http://localhost:4000/ordenes/507171c5-2c52-4b79-ba68-e0565d4d3ceb

### Para realizar una orden
POST http://localhost:4000/ordenes
Content-Type: application/json

{
    "productos": [
        {
            "id": "b10425ea-fd3f-4fff-b580-4c6361f48770",
            "cantidad": 2
        }
    ]
}

### Para actualizar el estado de una orden (solo ADMIN)
PATCH http://localhost:4000/ordenes/d7576046-b2db-4e68-b0ff-b51781532338/estado
Content-Type: application/json

{
    "estado": "PAGADO"
}

### Para subir una imagen a Cloudinary (solo ADMIN)
POST http://localhost:4000/admin/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="ejemplo.jpg"
Content-Type: image/jpeg

< ./ejemplo.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Crear preferencia de pago
POST http://localhost:4000/ordenes/507171c5-2c52-4b79-ba68-e0565d4d3ceb/pago


